# 01 — Dataset integrity, vehicle IDs, and route audit

This notebook covers Tasks 1 and 3–7. It reads every raw daily CSV directly from `data/`. It writes no cleaned, filtered, or intermediate dataset.

## Cleaning/interpretation log

- All identifier and route columns are read as strings. No numeric coercion is used for IDs.
- Timestamps are parsed only for validation; source values are not overwritten.
- Exact duplicates are counted within each daily file. Since filenames partition calendar dates, cross-file duplicates would require a timestamp/date inconsistency and are separately exposed by the filename-vs-timestamp check.
- Route normalization trims surrounding whitespace and changes only an integer-like decimal suffix (`44.0 → 44`). Leading zeroes, internal punctuation, suffixes, and decimal variants such as `49.1` are preserved.
- Full-name normalization is diagnostic only: uppercase, whitespace normalization, and accent removal. It is not used to force a route match.

In [1]:
from pathlib import Path
from collections import Counter, defaultdict
import re, unicodedata, warnings
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 180)
warnings.filterwarnings("ignore", category=pd.errors.DtypeWarning)

HERE = Path.cwd().resolve()
PROJECT = HERE.parent if HERE.name == "mob_tick_matching_robustness_check" else HERE
DATA = PROJECT / "data"
MOB_FILES = sorted((DATA / "mobility_data").glob("*.csv"))
TIX_FILES = sorted((DATA / "ticket_data").glob("*.csv"))
BAD_DATES = {"2026-03-18", "2026-03-19", "2026-03-20", "2026-03-22", "2026-03-28"}
RELIABLE_FILES_M = [p for p in MOB_FILES if p.stem not in BAD_DATES]
RELIABLE_DATES = {p.stem for p in RELIABLE_FILES_M}
RELIABLE_FILES_T = [p for p in TIX_FILES if p.stem in RELIABLE_DATES]

def canon_route(x):
    """Conservative formatting normalization; does not remove leading zeroes or punctuation."""
    if pd.isna(x): return pd.NA
    s = str(x).strip()
    return re.sub(r"^(\d+)\.0$", r"\1", s)

def canon_name(x):
    if pd.isna(x): return pd.NA
    s = unicodedata.normalize("NFKD", str(x))
    s = "".join(c for c in s if not unicodedata.combining(c)).upper().strip()
    return re.sub(r"\s+", " ", s)

print(f"Project: {PROJECT}")
print(f"Mobility files: {len(MOB_FILES)}; Ticket files: {len(TIX_FILES)}; reliable overlapping dates: {len(RELIABLE_DATES)}")

Project: /Users/pirin/Desktop/Under Grad Research/Netmob2026_data_challenge
Mobility files: 19; Ticket files: 31; reliable overlapping dates: 16

In [2]:
def audit_group(files, kind):
    relevant = (["id","timestamp","tripId","lat","lng","heading","lineId","lineName","headsign","direction"] if kind=="mobility" else
                ["transaction_date","anon_user_id","fare_type","vehicle_number","company_number","route_detail_id","integration_flag","card_type","debited_amount","view_type","route_name","day_type","day_period"])
    timecol = "timestamp" if kind=="mobility" else "transaction_date"
    rows=[]; missing=Counter(); dtypes={}; values=Counter(); duplicate_total=0
    malformed_total=0; filename_date_mismatch=0
    for p in files:
        df=pd.read_csv(p, dtype={c:"string" for c in relevant}, low_memory=False)
        parsed=pd.to_datetime(df[timecol], errors="coerce", utc=(kind=="ticket"))
        malformed=int(parsed.isna().sum())
        local_date=(parsed.dt.tz_convert("America/Sao_Paulo").dt.strftime("%Y-%m-%d") if kind=="ticket" else parsed.dt.strftime("%Y-%m-%d"))
        mismatch=int((local_date.notna() & local_date.ne(p.stem)).sum())
        dup=int(df.duplicated().sum())
        duplicate_total += dup; malformed_total += malformed; filename_date_mismatch += mismatch
        for c in relevant:
            if c in df:
                missing[c] += int(df[c].isna().sum() + df[c].fillna("").str.strip().eq("").sum())
                dtypes.setdefault(c,set()).add(str(df[c].dtype))
        rows.append({"file":p.name,"rows":len(df),"timestamp_min":parsed.min(),"timestamp_max":parsed.max(),"malformed_time":malformed,"exact_duplicates":dup,"file_date_mismatch":mismatch})
        values["rows"] += len(df)
    miss=pd.DataFrame({"column":list(missing),"missing_count":list(missing.values())})
    miss["missing_rate_pct"]=100*miss.missing_count/values["rows"]
    return pd.DataFrame(rows), miss.sort_values("missing_rate_pct",ascending=False), dtypes, {"rows":values["rows"],"duplicates":duplicate_total,"malformed":malformed_total,"file_date_mismatch":filename_date_mismatch}

mob_daily,mob_missing,mob_dtypes,mob_totals=audit_group(MOB_FILES,"mobility")
tix_daily,tix_missing,tix_dtypes,tix_totals=audit_group(TIX_FILES,"ticket")
display(Markdown("## A. Dataset integrity — files, dates, row counts, ranges"))
display(mob_daily)
display(tix_daily)
display(pd.DataFrame([{"dataset":"Mobility",**mob_totals},{"dataset":"Ticket",**tix_totals}]))
display(Markdown("### Missingness of matching-relevant columns")); display(mob_missing); display(tix_missing)
display(Markdown("### Actual pandas dtypes under explicit identifier-as-string loading"))
display(pd.DataFrame({"Mobility":pd.Series({k:", ".join(v) for k,v in mob_dtypes.items()}),"Ticket":pd.Series({k:", ".join(v) for k,v in tix_dtypes.items()})}))

## A. Dataset integrity — files, dates, row counts, ranges

              file     rows       timestamp_min       timestamp_max  malformed_time  exact_duplicates  file_date_mismatch
0   2026-03-11.csv   950855 2026-03-11 00:00:07 2026-03-11 23:59:52               0                 0                   0
1   2026-03-12.csv   985831 2026-03-12 00:00:07 2026-03-12 23:59:52               0                 0                   0
2   2026-03-13.csv  1053712 2026-03-13 00:00:07 2026-03-13 23:59:52               0                 0                   0
3   2026-03-14.csv   774648 2026-03-14 00:00:07 2026-03-14 23:59:54               0                 0                   0
4   2026-03-15.csv   481931 2026-03-15 00:00:09 2026-03-15 23:59:50               0                 0                   0
5   2026-03-16.csv   651833 2026-03-16 00:00:09 2026-03-16 23:59:46               0                 0                   0
6   2026-03-17.csv   226412 2026-03-17 00:00:01 2026-03-17 10:46:51               0                 0                   0
7   2026-03-20.csv   420493 2026-03-20 14:52:13 2026-03-20 23:59:50               0                 0                   0
8   2026-03-21.csv   555022 2026-03-21 00:00:05 2026-03-21 23:58:19               0                 0                   0
9   2026-03-22.csv    65993 2026-03-22 00:04:06 2026-03-22 23:57:37               0                 0                   0
10  2026-03-23.csv   802536 2026-03-23 00:03:26 2026-03-23 23:59:48               0                 0                   0
11  2026-03-24.csv  1132295 2026-03-24 00:00:03 2026-03-24 23:59:49               0                 0                   0
12  2026-03-25.csv  1043626 2026-03-25 00:00:04 2026-03-25 23:59:46               0                 0                   0
13  2026-03-26.csv  1062708 2026-03-26 00:00:01 2026-03-26 23:59:58               0                 0                   0
14  2026-03-27.csv  1067407 2026-03-27 00:00:12 2026-03-27 23:59:58               0                 0                   0
15  2026-03-28.csv   328626 2026-03-28 00:00:13 2026-03-28 23:56:11               0                 0                   0
16  2026-03-29.csv   504273 2026-03-29 00:00:01 2026-03-29 23:31:48               0                 0                   0
17  2026-03-30.csv   847024 2026-03-30 00:00:00 2026-03-30 23:59:46               0                 0                   0
18  2026-03-31.csv   895242 2026-03-31 00:00:01 2026-03-31 23:37:32               0                 0                   0

              file    rows             timestamp_min             timestamp_max  malformed_time  exact_duplicates  file_date_mismatch
0   2026-03-01.csv   63379 2026-03-01 03:00:02+00:00 2026-03-02 02:59:38+00:00               0                 0                   0
1   2026-03-02.csv  258057 2026-03-02 03:00:04+00:00 2026-03-03 02:59:05+00:00               0                19                   0
2   2026-03-03.csv  267760 2026-03-03 03:01:12+00:00 2026-03-04 02:59:39+00:00               0               699                   0
3   2026-03-04.csv  265886 2026-03-04 03:01:36+00:00 2026-03-05 02:58:44+00:00               0                21                   0
4   2026-03-05.csv  269360 2026-03-05 03:01:40+00:00 2026-03-06 02:59:50+00:00               0               341                   0
5   2026-03-06.csv  266077 2026-03-06 03:04:31+00:00 2026-03-07 02:58:11+00:00               0                20                   0
6   2026-03-07.csv  133017 2026-03-07 03:00:03+00:00 2026-03-08 02:59:59+00:00               0                11                   0
7   2026-03-08.csv   71337 2026-03-08 03:00:04+00:00 2026-03-09 02:58:27+00:00               0                 2                   0
8   2026-03-09.csv  242639 2026-03-09 03:03:05+00:00 2026-03-10 02:59:01+00:00               0                19                   0
9   2026-03-10.csv  274380 2026-03-10 03:01:12+00:00 2026-03-11 02:59:02+00:00               0               467                   0
10  2026-03-11.csv  267132 2026-03-11 03:01:52+00:00 2026-03-12 02:59:22+00:00               0                18                   0
11  2026-03-12.csv  270418 2026-03-12 03:00:29+00:00 2026-03-13 02:59:55+00:00               0                35                   0
12  2026-03-13.csv  262015 2026-03-13 03:01:09+00:00 2026-03-14 02:59:40+00:00               0               468                   0
13  2026-03-14.csv  124486 2026-03-14 03:00:10+00:00 2026-03-15 02:59:17+00:00               0                 2                   0
14  2026-03-15.csv   68557 2026-03-15 03:02:12+00:00 2026-03-16 02:55:35+00:00               0                 0                   0
15  2026-03-16.csv  271189 2026-03-16 03:00:02+00:00 2026-03-17 02:59:10+00:00               0               648                   0
16  2026-03-17.csv  279404 2026-03-17 03:03:01+00:00 2026-03-18 02:59:17+00:00               0              1251                   0
17  2026-03-18.csv  276846 2026-03-18 03:01:24+00:00 2026-03-19 02:59:01+00:00               0               875                   0
18  2026-03-19.csv  278182 2026-03-19 03:02:12+00:00 2026-03-20 02:59:49+00:00               0                16                   0
19  2026-03-20.csv  259808 2026-03-20 03:03:02+00:00 2026-03-21 02:59:59+00:00               0                16                   0
20  2026-03-21.csv  125401 2026-03-21 03:00:17+00:00 2026-03-22 02:57:46+00:00               0                 1                   0
21  2026-03-22.csv   70310 2026-03-22 03:00:43+00:00 2026-03-23 02:59:41+00:00               0                 1                   0
22  2026-03-23.csv  264903 2026-03-23 03:03:43+00:00 2026-03-24 02:58:30+00:00               0                21                   0
23  2026-03-24.csv  280452 2026-03-24 03:01:46+00:00 2026-03-25 02:59:56+00:00               0               989                   0
24  2026-03-25.csv  276473 2026-03-25 03:00:10+00:00 2026-03-26 02:59:55+00:00               0               865                   0
25  2026-03-26.csv  280033 2026-03-26 03:00:00+00:00 2026-03-27 02:59:21+00:00               0               707                   0
26  2026-03-27.csv  269257 2026-03-27 03:01:44+00:00 2026-03-28 02:59:39+00:00               0                21                   0
27  2026-03-28.csv  131448 2026-03-28 03:00:32+00:00 2026-03-29 02:59:29+00:00               0                 0                   0
28  2026-03-29.csv   72859 2026-03-29 03:05:00+00:00 2026-03-30 02:59:52+00:00               0                 0                   0
29  2026-03-30.csv  271984 2026-03-30 03:00:02+00:00 2026-03-31 02:56:48+00:00               0               175                   0
30  2026-03-31.csv  277632 2026-03-31 03:02:24+00:00 2026-04-01 02:59:57+00:00               0                26                   0

    dataset      rows  duplicates  malformed  file_date_mismatch
0  Mobility  13850467           0          0                   0
1    Ticket   6790681        7734          0                   0

### Missingness of matching-relevant columns

      column  missing_count  missing_rate_pct
0         id              0               0.0
1  timestamp              0               0.0
2     tripId              0               0.0
3        lat              0               0.0
4        lng              0               0.0
5    heading              0               0.0
6     lineId              0               0.0
7   lineName              0               0.0
8   headsign              0               0.0
9  direction              0               0.0

              column  missing_count  missing_rate_pct
0   transaction_date              0               0.0
1       anon_user_id              0               0.0
2          fare_type              0               0.0
3     vehicle_number              0               0.0
4     company_number              0               0.0
5    route_detail_id              0               0.0
6   integration_flag              0               0.0
7          card_type              0               0.0
8     debited_amount              0               0.0
9          view_type              0               0.0
10        route_name              0               0.0
11          day_type              0               0.0
12        day_period              0               0.0

### Actual pandas dtypes under explicit identifier-as-string loading

                 Mobility  Ticket
anon_user_id          NaN  string
card_type             NaN  string
company_number        NaN  string
day_period            NaN  string
day_type              NaN  string
debited_amount        NaN  string
direction          string     NaN
fare_type             NaN  string
heading            string     NaN
headsign           string     NaN
id                 string     NaN
integration_flag      NaN  string
lat                string     NaN
lineId             string     NaN
lineName           string     NaN
lng                string     NaN
route_detail_id       NaN  string
route_name            NaN  string
timestamp          string     NaN
transaction_date      NaN  string
tripId             string     NaN
vehicle_number        NaN  string
view_type             NaN  string

In [3]:
# Vehicle summaries are accumulated without retaining all raw rows.
mob_id_obs=Counter(); mob_id_days=defaultdict(set); mob_active=[]; mob_first={}; mob_last={}
tix_key_obs=Counter(); tix_key_days=defaultdict(set); tix_active=[]; vehicle_companies=defaultdict(set)
mob_raw_routes=Counter(); tix_raw_routes=Counter(); mob_names=Counter(); tix_names=Counter()
tix_route_views=defaultdict(Counter); mob_route_names=defaultdict(Counter)
tix_detail_route=defaultdict(set); tix_detail_view=defaultdict(set); tix_detail_company=defaultdict(set); route_details=defaultdict(set)

for p in MOB_FILES:
    df=pd.read_csv(p,usecols=["id","timestamp","lineId","lineName"],dtype="string")
    ids=df.id.dropna(); mob_id_obs.update(ids); active=set(ids); mob_active.append((p.stem,len(active)))
    for x in active: mob_id_days[x].add(p.stem)
    ts=pd.to_datetime(df.timestamp,errors="coerce")
    for x,g in pd.DataFrame({"id":df.id,"ts":ts}).dropna().groupby("id").ts:
        lo,hi=g.min(),g.max(); mob_first[x]=min(mob_first.get(x,lo),lo); mob_last[x]=max(mob_last.get(x,hi),hi)
    mob_raw_routes.update(df.lineId.dropna()); mob_names.update(df.lineName.dropna())
    for (r,n),cnt in df.groupby(["lineId","lineName"],dropna=True).size().items(): mob_route_names[r][n]+=int(cnt)

for p in TIX_FILES:
    df=pd.read_csv(p,usecols=["vehicle_number","company_number","route_name","view_type","route_detail_id"],dtype="string")
    for v,c in df[["vehicle_number","company_number"]].dropna().drop_duplicates().itertuples(index=False): vehicle_companies[v].add(c)
    keys=df.vehicle_number.dropna(); tix_key_obs.update(keys); active=set(keys); tix_active.append((p.stem,len(active)))
    for x in active: tix_key_days[x].add(p.stem)
    tix_raw_routes.update(df.route_name.dropna()); tix_names.update(df.view_type.dropna())
    for (r,n),cnt in df.groupby(["route_name","view_type"],dropna=True).size().items(): tix_route_views[r][n]+=int(cnt)
    for r,d,v,c in df[["route_name","route_detail_id","view_type","company_number"]].dropna(subset=["route_name","route_detail_id"]).drop_duplicates().itertuples(index=False):
        route_details[r].add(d); tix_detail_route[d].add(r); tix_detail_view[d].add(v); tix_detail_company[d].add(c)

mob_vehicle=pd.DataFrame({"id":list(mob_id_obs),"observations":[mob_id_obs[x] for x in mob_id_obs],"days_observed":[len(mob_id_days[x]) for x in mob_id_obs],"first_seen":[mob_first.get(x) for x in mob_id_obs],"last_seen":[mob_last.get(x) for x in mob_id_obs]}).sort_values("observations",ascending=False)
tix_vehicle=pd.DataFrame({"vehicle_number":list(tix_key_obs),"transactions":[tix_key_obs[x] for x in tix_key_obs],"days_observed":[len(tix_key_days[x]) for x in tix_key_obs],"company_count":[len(vehicle_companies[x]) for x in tix_key_obs],"companies":[",".join(sorted(vehicle_companies[x])) for x in tix_key_obs]}).sort_values("transactions",ascending=False)
display(Markdown("## B. Vehicle ID structure"))
display(pd.DataFrame({"metric":["unique vehicles","median days/vehicle","min days/vehicle","max days/vehicle"],"Ticket":[len(tix_vehicle),tix_vehicle.days_observed.median(),tix_vehicle.days_observed.min(),tix_vehicle.days_observed.max()],"Mobility":[len(mob_vehicle),mob_vehicle.days_observed.median(),mob_vehicle.days_observed.min(),mob_vehicle.days_observed.max()]}))
display(Markdown("### Active vehicles per day")); display(pd.DataFrame(tix_active,columns=["date","Ticket_active"]).merge(pd.DataFrame(mob_active,columns=["date","Mobility_active"]),on="date",how="outer"))
display(Markdown("### Ticket vehicle summary (complete table)")); display(tix_vehicle)
display(Markdown("### Mobility ID summary (complete table; inspect short spans as replacement clues)")); display(mob_vehicle)
multi_company=tix_vehicle.query("company_count > 1")
display(Markdown(f"### `ticket.groupby('vehicle_number')['company_number'].nunique()` result: {len(multi_company)} multi-company vehicle numbers")); display(multi_company)

## B. Vehicle ID structure

                metric  Ticket  Mobility
0      unique vehicles   556.0     527.0
1  median days/vehicle    25.0      13.0
2     min days/vehicle     1.0       1.0
3     max days/vehicle    31.0      19.0

### Active vehicles per day

          date  Ticket_active  Mobility_active
0   2026-03-01            196              NaN
1   2026-03-02            486              NaN
2   2026-03-03            487              NaN
3   2026-03-04            490              NaN
4   2026-03-05            491              NaN
5   2026-03-06            487              NaN
6   2026-03-07            289              NaN
7   2026-03-08            196              NaN
8   2026-03-09            489              NaN
9   2026-03-10            487              NaN
10  2026-03-11            495            380.0
11  2026-03-12            495            393.0
12  2026-03-13            493            438.0
13  2026-03-14            288            318.0
14  2026-03-15            195            213.0
15  2026-03-16            503            260.0
16  2026-03-17            504            212.0
17  2026-03-18            498              NaN
18  2026-03-19            497              NaN
19  2026-03-20            494            385.0
20  2026-03-21            292            296.0
21  2026-03-22            197            226.0
22  2026-03-23            489            411.0
23  2026-03-24            500            404.0
24  2026-03-25            494            365.0
25  2026-03-26            493            370.0
26  2026-03-27            495            370.0
27  2026-03-28            285            155.0
28  2026-03-29            188            226.0
29  2026-03-30            497            344.0
30  2026-03-31            500            327.0

### Ticket vehicle summary (complete table)

    vehicle_number  transactions  days_observed  company_count companies
76           11049         21886             31              1         3
125          24116         20478             26              1        56
204          13061         20157             28              1         2
116          11151         20064             29              1         3
92           24115         19904             26              1        56
..             ...           ...            ...            ...       ...
535          21148           160              1              1        56
554          21029           157              1              1         3
423          23034           149              1              1        56
538          21006           103              1              1         3
549          21013            33              1              1         3

[556 rows x 5 columns]

### Mobility ID summary (complete table; inspect short spans as replacement clues)

         id  observations  days_observed          first_seen           last_seen
465  123460         55219             17 2026-03-13 13:55:22 2026-03-31 23:37:32
28    97095         52892             19 2026-03-11 00:00:07 2026-03-31 23:37:32
33    99133         51673             19 2026-03-11 00:00:07 2026-03-31 23:37:32
29    97110         50766             19 2026-03-11 00:00:07 2026-03-31 22:54:47
461  116875         50491             16 2026-03-13 13:55:22 2026-03-31 22:43:32
..      ...           ...            ...                 ...                 ...
412   72722           900              3 2026-03-12 14:43:24 2026-03-29 18:54:19
524   83518           875              1 2026-03-26 15:43:21 2026-03-26 20:45:19
504   99160           779              1 2026-03-16 06:02:09 2026-03-16 19:14:35
525   72757           667              1 2026-03-27 17:04:59 2026-03-27 19:51:30
364   72702           133              1 2026-03-11 15:38:26 2026-03-11 16:11:29

[527 rows x 5 columns]

### `ticket.groupby('vehicle_number')['company_number'].nunique()` result: 23 multi-company vehicle numbers

    vehicle_number  transactions  days_observed  company_count companies
40           11077         15917             28              2      22,3
272          11040         14491             25              2      22,3
382          12010         13865             24              2      22,3
314          11073         13764             23              2      22,3
298          11071         13467             26              2      22,3
56           11027         13441             27              2      22,3
218          11029         13368             25              2      22,3
222          11028         13354             25              2      22,3
209          11016         13038             27              2      22,3
157          11076         12194             28              2      22,3
244          12009         12075             22              2      22,3
43           11078         12012             28              2      22,3
329          11079         11915             25              2      22,3
235          11127         11805             26              2      22,3
359          11080         11198             23              2      22,3
30           11084         10964             26              2      22,3
366          11058         10464             26              2      22,3
418          11074          9483             23              2      22,3
246          11056          8453             18              2      22,3
529          12001          7751             15              2      22,3
473          11126          7350             14              2      22,3
343          11075          6961             20              2      22,3
520          14040          3103             13              2      11,2

In [4]:
# Exact ID overlap sanity check, preserving strings.
tset=set(tix_vehicle.vehicle_number); mset=set(mob_vehicle.id); overlap=sorted(tset&mset)
def numeric_range(s):
    x=pd.to_numeric(pd.Series(list(s)),errors="coerce")
    return {"numeric_parse_pct":100*x.notna().mean(),"min":x.min(),"max":x.max()}
display(Markdown("### Exact identifier overlap"))
display(pd.DataFrame([{"side":"Ticket vehicle_number","unique":len(tset),**numeric_range(tset)},{"side":"Mobility id","unique":len(mset),**numeric_range(mset)}]))
display(pd.DataFrame({"exact_intersection":overlap}))
print({"intersection_n":len(overlap),"pct_ticket_ids":100*len(overlap)/len(tset),"pct_mobility_ids":100*len(overlap)/len(mset)})

### Exact identifier overlap

                    side  unique  numeric_parse_pct    min     max
0  Ticket vehicle_number     556              100.0   2001   24142
1            Mobility id     527              100.0  52243  136462

Empty DataFrame
Columns: [exact_intersection]
Index: []

{'intersection_n': 0, 'pct_ticket_ids': 0.0, 'pct_mobility_ids': 0.0}

In [5]:
# Raw route formats and conservative normalization.
traw=set(tix_raw_routes); mraw=set(mob_raw_routes)
tcanon={canon_route(x) for x in traw}; mcanon={canon_route(x) for x in mraw}; inter=tcanon&mcanon
format_flags=lambda vals: pd.DataFrame({"raw":sorted(vals),"canonical":[canon_route(x) for x in sorted(vals)],"leading_zero":[bool(re.match(r"^0\d",x)) for x in sorted(vals)],"decimal":[bool(re.search(r"\.\d+$",x)) for x in sorted(vals)],"has_space":[x!=x.strip() or " " in x for x in sorted(vals)]})
display(Markdown("## C. Route compatibility — raw formats")); display(format_flags(traw)); display(format_flags(mraw))
route_summary=pd.DataFrame([{"Ticket_unique":len(tcanon),"Mobility_unique":len(mcanon),"intersection":len(inter),"Ticket_only":len(tcanon-inter),"Mobility_only":len(mcanon-inter)}])
display(route_summary); print("Ticket-only:",sorted(tcanon-inter)); print("Mobility-only:",sorted(mcanon-inter))
tix_matched=sum(n for r,n in tix_raw_routes.items() if canon_route(r) in mcanon); mob_matched=sum(n for r,n in mob_raw_routes.items() if canon_route(r) in tcanon)
print({"pct_ticket_transactions_route_present_in_mobility":100*tix_matched/sum(tix_raw_routes.values()),"pct_mobility_observations_route_present_in_ticket":100*mob_matched/sum(mob_raw_routes.values())})

def stability_table(mapping,label):
    rows=[]
    for k,c in mapping.items():
        rows.append({label:k,"distinct_names":len(c),"dominant_name":c.most_common(1)[0][0],"dominant_share":c.most_common(1)[0][1]/sum(c.values()),"all_names":" | ".join(c)})
    return pd.DataFrame(rows).sort_values(["distinct_names",label],ascending=[False,True])
tmap=stability_table(tix_route_views,"route_name"); mmap=stability_table(mob_route_names,"lineId")
display(Markdown("### Within-system route-to-name stability")); display(tmap); display(mmap)

exact_names=set(tix_names)&set(mob_names); canon_t={canon_name(x) for x in tix_names}; canon_m={canon_name(x) for x in mob_names}
print({"exact_full_name_intersection":len(exact_names),"normalized_full_name_intersection":len(canon_t&canon_m),"ticket_unique_names":len(tix_names),"mobility_unique_names":len(mob_names)})
paired=[]
for r in sorted(inter):
    tv=Counter(); mv=Counter()
    for raw,c in tix_route_views.items():
        if canon_route(raw)==r: tv.update(c)
    for raw,c in mob_route_names.items():
        if canon_route(raw)==r: mv.update(c)
    tn=tv.most_common(1)[0][0] if tv else None; mn=mv.most_common(1)[0][0] if mv else None
    paired.append({"route":r,"Ticket_view_type":tn,"Mobility_lineName":mn,"exact":tn==mn,"case_space_accent_equal":canon_name(tn)==canon_name(mn)})
display(Markdown("### Dominant full names for shared route codes (diagnostic; no fuzzy forcing)")); display(pd.DataFrame(paired))

## C. Route compatibility — raw formats

      raw canonical  leading_zero  decimal  has_space
0     026       026          True    False      False
1      15        15         False    False      False
2      17        17         False    False      False
3     17J       17J         False    False      False
4      21        21         False    False      False
5      22        22         False    False      False
6    24.A      24.A         False    False      False
7     26A       26A         False    False      False
8      28        28         False    False      False
9       3         3         False    False      False
10     30        30         False    False      False
11     31        31         False    False      False
12     32        32         False    False      False
13     33        33         False    False      False
14    33F       33F         False    False      False
15     34        34         False    False      False
16    34A       34A         False    False      False
17     35        35         False    False      False
18     36        36         False    False      False
19     37        37         False    False      False
20    38A       38A         False    False      False
21    39A       39A         False    False      False
22     40        40         False    False      False
23   41BC      41BC         False    False      False
24   41JB      41JB         False    False      False
25   42SL      42SL         False    False      False
26    42T       42T         False    False      False
27   43.2      43.2         False     True      False
28     44        44         False    False      False
29     45        45         False    False      False
30     46        46         False    False      False
31    46P       46P         False    False      False
32     47        47         False    False      False
33    47A       47A         False    False      False
34    47B       47B         False    False      False
35     48        48         False    False      False
36    48B       48B         False    False      False
37   48SP      48SP         False    False      False
38   49.1      49.1         False     True      False
39   49.2      49.2         False     True      False
40     52        52         False    False      False
41    52A       52A         False    False      False
42     53        53         False    False      False
43     54        54         False    False      False
44    55A       55A         False    False      False
45     56        56         False    False      False
46     57        57         False    False      False
47  580.M     580.M         False    False      False
48     60        60         False    False      False
49     61        61         False    False      False
50     62        62         False    False      False
51    62B       62B         False    False      False
52    66C       66C         False    False      False
53     67        67         False    False      False
54    OC1       OC1         False    False      False
55    OC2       OC2         False    False      False
56    OC3       OC3         False    False      False
57   OC3A      OC3A         False    False      False

     raw canonical  leading_zero  decimal  has_space
0     03        03          True    False      False
1     15        15         False    False      False
2     21        21         False    False      False
3     22        22         False    False      False
4     24        24         False    False      False
5   24.0        24         False     True      False
6     26        26         False    False      False
7    26A       26A         False    False      False
8     28        28         False    False      False
9     30        30         False    False      False
10  30.0        30         False     True      False
11    31        31         False    False      False
12  31.0        31         False     True      False
13    32        32         False    False      False
14    33        33         False    False      False
15   34A       34A         False    False      False
16   34B       34B         False    False      False
17    35        35         False    False      False
18    36        36         False    False      False
19  36.0        36         False     True      False
20    37        37         False    False      False
21   38A       38A         False    False      False
22   39A       39A         False    False      False
23    40        40         False    False      False
24  41BC      41BC         False    False      False
25  41JB      41JB         False    False      False
26   42S       42S         False    False      False
27   42T       42T         False    False      False
28  43.2      43.2         False     True      False
29    44        44         False    False      False
30  44.0        44         False     True      False
31    45        45         False    False      False
32  45.0        45         False     True      False
33    46        46         False    False      False
34    47        47         False    False      False
35  47.0        47         False     True      False
36   47A       47A         False    False      False
37   47B       47B         False    False      False
38    48        48         False    False      False
39   48B       48B         False    False      False
40  48SP      48SP         False    False      False
41  49.1      49.1         False     True      False
42  49.2      49.2         False     True      False
43    52        52         False    False      False
44   52A       52A         False    False      False
45    53        53         False    False      False
46    54        54         False    False      False
47   55A       55A         False    False      False
48    57        57         False    False      False
49    60        60         False    False      False
50  60.0        60         False     True      False
51    61        61         False    False      False
52  61.0        61         False     True      False
53    62        62         False    False      False
54  62.0        62         False     True      False
55   66C       66C         False    False      False
56    67        67         False    False      False
57  67.0        67         False     True      False
58   OC1       OC1         False    False      False
59   OC2       OC2         False    False      False
60   OC3       OC3         False    False      False
61  OC3A      OC3A         False    False      False

   Ticket_unique  Mobility_unique  intersection  Ticket_only  Mobility_only
0             58               51            46           12              5

Ticket-only: ['026', '17', '17J', '24.A', '3', '33F', '34', '42SL', '46P', '56', '580.M', '62B']
Mobility-only: ['03', '24', '26', '34B', '42S']
{'pct_ticket_transactions_route_present_in_mobility': 92.74738424614556, 'pct_mobility_observations_route_present_in_ticket': 96.46061753730037}

### Within-system route-to-name stability

   route_name  distinct_names                                  dominant_name  dominant_share                                          all_names
24        42T               2              BARRETO - CENTRO (VIA RODOVIÁRIA)        0.762153  BARRETO - CENTRO (VIA RODOVIARIA) | BARRETO - ...
0         026               1                                       FLORÁLIA        1.000000                                           FLORÁLIA
1          15               1                     ILHA DA CONCEIÇÃO - CENTRO        1.000000                         ILHA DA CONCEIÇÃO - CENTRO
2          17               1             SÃO FRANCISCO - CENTRO (VIA FROES)        1.000000                 SÃO FRANCISCO - CENTRO (VIA FROES)
3         17J               1                             JURUJUBA VIA FROES        1.000000                                 JURUJUBA VIA FROES
4          21               1                               FONSECA - CENTRO        1.000000                                   FONSECA - CENTRO
5          22               1                        LARGO DO MOURA - CENTRO        1.000000                            LARGO DO MOURA - CENTRO
6        24.A               1                             PALMEIRAS - CENTRO        1.000000                                 PALMEIRAS - CENTRO
7         26A               1                          MORRO DO CÉU - CENTRO        1.000000                              MORRO DO CÉU - CENTRO
46         28               1     CENTRO CIRCULAR LARGO CRAVINHO VIA FONSECA        1.000000         CENTRO CIRCULAR LARGO CRAVINHO VIA FONSECA
57          3               1                      BAIRRO DE FÁTIMA - CENTRO        1.000000                          BAIRRO DE FÁTIMA - CENTRO
8          30               1                                 MARTINS TORRES        1.000000                                     MARTINS TORRES
9          31               1                       PONTA DA AREIA - BELTRÃO        1.000000                           PONTA DA AREIA - BELTRÃO
10         32               1                             CACHOEIRA - CENTRO        1.000000                                 CACHOEIRA - CENTRO
11         33               1                              JURUJUBA - CENTRO        1.000000                                  JURUJUBA - CENTRO
12        33F               1              JURUJUBA (VIA FORTALEZA STA CRUZ)        1.000000                  JURUJUBA (VIA FORTALEZA STA CRUZ)
13         34               1                        LARGO BATALHA - CUBANGO        1.000000                            LARGO BATALHA - CUBANGO
14        34A               1                  L.B. - CENTRO (VIA V. JARDIM)        1.000000                      L.B. - CENTRO (VIA V. JARDIM)
15         35               1                              BALDEDOR - CENTRO        1.000000                                  BALDEDOR - CENTRO
16         36               1                                  SAPE - CENTRO        1.000000                                      SAPE - CENTRO
17         37               1                      PARQUE DA COLINA - CENTRO        1.000000                          PARQUE DA COLINA - CENTRO
18        38A               1          ITAIPU - CENTRO (VIA ENGENHO DO MATO)        1.000000              ITAIPU - CENTRO (VIA ENGENHO DO MATO)
19        39A               1              PIRATININGA - CENTRO (VIA CAFUBA)        1.000000                  PIRATININGA - CENTRO (VIA CAFUBA)
20         40               1                                MACEIO - CENTRO        1.000000                                    MACEIO - CENTRO
21       41BC               1   VENDA DA CRUZ - CENTRO VIA BENJAMIN CONSTANT        1.000000       VENDA DA CRUZ - CENTRO VIA BENJAMIN CONSTANT
22       41JB               1         VENDA DA CRUZ - CENTRO VIA JOÃO BRASIL        1.000000             VENDA DA CRUZ - CENTRO VIA JOÃO BRASIL
23       42SL               1            BARRETO - CENTRO (VIA SAO LOURENÇO)        1.000000                BARRETO - CENTRO (VIA SAO LOURENÇO)
47       43.2               1                  CIRCULAR VIA 22 DE NOVEMBRO A        1.000000                      CIRCULAR VIA 22 DE NOVEMBRO A
25         44               1                              ITITIOCA - CENTRO        1.000000                                  ITITIOCA - CENTRO
26         45               1                               CUBANGO - CENTRO        1.000000                                   CUBANGO - CENTRO
27         46               1                      VÁRZEA DAS MOÇAS - CENTRO        1.000000                          VÁRZEA DAS MOÇAS - CENTRO
48        46P               1                                RJ 106 X CENTRO        1.000000                                    RJ 106 X CENTRO
28         47               1                                   CANTO DO RIO        1.000000                                       CANTO DO RIO
49        47A               1                       CAMPUS DA UFF - CIRCULAR        1.000000                           CAMPUS DA UFF - CIRCULAR
29        47B               1                      CAMPUS DA UFF - VIA MUSEU        1.000000                          CAMPUS DA UFF - VIA MUSEU
30         48               1                           RIO DO OURO - CENTRO        1.000000                               RIO DO OURO - CENTRO
50        48B               1                                BOSQUE - CENTRO        1.000000                                    BOSQUE - CENTRO
51       48SP               1                  RIO DO OURO - PRAIA DE ICARAI        1.000000                      RIO DO OURO - PRAIA DE ICARAI
31       49.1               1                     CIRCULAR VIA D LIMA CASTRO        1.000000                         CIRCULAR VIA D LIMA CASTRO
32       49.2               1                     CIRCULAR VIA D LIMA CASTRO        1.000000                         CIRCULAR VIA D LIMA CASTRO
33         52               1             BALDEADOR - ITAIPU (VIA CANTAGALO)        1.000000                 BALDEADOR - ITAIPU (VIA CANTAGALO)
52        52A               1                           BALDEADOR - CHARITAS        1.000000                               BALDEADOR - CHARITAS
34         53               1                            SANTA ROSA - CENTRO        1.000000                                SANTA ROSA - CENTRO
53         54               1                             SAPE - PIRATININGA        1.000000                                 SAPE - PIRATININGA
35        55A               1  VARZEA DAS MOÇAS X PIRATININGA - (VIA CAFUBÁ)        1.000000      VARZEA DAS MOÇAS X PIRATININGA - (VIA CAFUBÁ)
54         56               1                      VARZEA DAS MOÇAS - ITAIPU        1.000000                          VARZEA DAS MOÇAS - ITAIPU
36         57               1              (CIRCULAR VIA F. VARELA/M. FRIAS)        1.000000                  (CIRCULAR VIA F. VARELA/M. FRIAS)
37      580.M               1          NITERÓI - TRIBOBÓ (VIA SANTA BÁRBARA)        1.000000              NITERÓI - TRIBOBÓ (VIA SANTA BÁRBARA)
38         60               1                     ILHA DA CONCEIÇÃO - ICARAÍ        1.000000                         ILHA DA CONCEIÇÃO - ICARAÍ
39         61               1                         VENDA DA CRUZ - ICARAÍ        1.000000                             VENDA DA CRUZ - ICARAÍ
56         62               1                             FONSECA - CHARITAS        1.000000                                 FONSECA - CHARITAS
40        62B               1                       SANTA BÁRBARA - CHARITAS        1.000000                           SANTA BÁRBARA - CHARITAS
55        66C               1               SÃO LOURENÇO - CENTRO (CIRCULAR)        1.000000                   SÃO LOURENÇO - CENTRO (CIRCULAR)
41         67               1                       CENTRO X MORRO DO CASTRO        1.000000                           CENTRO X MORRO DO CASTRO
42        OC1               1                PIRATININGA X CENTRO (VIA BHLS)        1.000000                    PIRATININGA X CENTRO (VIA BHLS)
43        OC2               1                   ITAIPU X CENTRO - (VIA BHLS)        1.000000                       ITAIPU X CENTRO - (VIA BHLS)
44        OC3               1           ITAIPU X CENTRO - (VIA PRAIA ICARAÍ)        1.000000               ITAIPU X CENTRO - (VIA PRAIA ICARAÍ)
45       OC3A               1            ITAIPU X CENTRO VIA ENGENHO DO MATO        1.000000                ITAIPU X CENTRO VIA ENGENHO DO MATO

   lineId  distinct_names                                     dominant_name  dominant_share                                         all_names
54     03               1                         CENTRO X BAIRRO DE FÁTIMA             1.0                         CENTRO X BAIRRO DE FÁTIMA
0      15               1                           ILHA CONCEIÇÃO X CENTRO             1.0                           ILHA CONCEIÇÃO X CENTRO
1      21               1                    BONFIM X TERMINAL JOÃO GOULART             1.0                    BONFIM X TERMINAL JOÃO GOULART
2      22               1                           BONFIM X AMARAL PEIXOTO             1.0                           BONFIM X AMARAL PEIXOTO
3      24               1  PALMEIRAS X TERMINAL JOÃO GOULART (VIA GRAGOATÁ)             1.0  PALMEIRAS X TERMINAL JOÃO GOULART (VIA GRAGOATÁ)
55   24.0               1  PALMEIRAS X TERMINAL JOÃO GOULART (VIA GRAGOATÁ)             1.0  PALMEIRAS X TERMINAL JOÃO GOULART (VIA GRAGOATÁ)
4      26               1                                 FLORÁRIA X CENTRO             1.0                                 FLORÁRIA X CENTRO
5     26A               1                                MORRO CÉU X CENTRO             1.0                                MORRO CÉU X CENTRO
6      28               1                LARGO DO CRAVINHO X AMARAL PEIXOTO             1.0                LARGO DO CRAVINHO X AMARAL PEIXOTO
46     30               1                                    Martins Torres             1.0                                    Martins Torres
50   30.0               1                                    Martins Torres             1.0                                    Martins Torres
7      31               1                                    PONTA DA AREIA             1.0                                    PONTA DA AREIA
56   31.0               1                                    PONTA DA AREIA             1.0                                    PONTA DA AREIA
8      32               1                   CACHOEIRA X TERMINAL RODOVIARIO             1.0                   CACHOEIRA X TERMINAL RODOVIARIO
9      33               1                    JURUJUBA X TERMINAL RODOVIARIO             1.0                    JURUJUBA X TERMINAL RODOVIARIO
10    34A               1                         LARGO DA BATALHA X CENTRO             1.0                         LARGO DA BATALHA X CENTRO
11    34B               1                        LARGO DA BATALHA X CUBANGO             1.0                        LARGO DA BATALHA X CUBANGO
12     35               1                                BALDEADOR X CENTRO             1.0                                BALDEADOR X CENTRO
13     36               1                                     SAPÊ X CENTRO             1.0                                     SAPÊ X CENTRO
57   36.0               1                                     SAPÊ X CENTRO             1.0                                     SAPÊ X CENTRO
14     37               1                         PARQUE DA COLINA X CENTRO             1.0                         PARQUE DA COLINA X CENTRO
15    38A               1                 ITAIPU X CENTRO (VIA ENG DO MATO)             1.0                 ITAIPU X CENTRO (VIA ENG DO MATO)
16    39A               1                              PIRATININGA X CENTRO             1.0                              PIRATININGA X CENTRO
17     40               1                                   MACEIÓ X CENTRO             1.0                                   MACEIÓ X CENTRO
18   41BC               1  VENDA DA CRUZ X TERMINAL - VIA BENJAMIN CONSTANT             1.0  VENDA DA CRUZ X TERMINAL - VIA BENJAMIN CONSTANT
19   41JB               1        VENDA DA CRUZ X TERMINAL - VIA JOAO BRASIL             1.0        VENDA DA CRUZ X TERMINAL - VIA JOAO BRASIL
20    42S               1                          BARRETO X AMARAL PEIXOTO             1.0                          BARRETO X AMARAL PEIXOTO
21    42T               1                          VENDA DA CRUZ X TERMINAL             1.0                          VENDA DA CRUZ X TERMINAL
22   43.2               1    CUBANGO ( 22 NOVEMBRO) X TERMINAL JOÃO GOULART             1.0    CUBANGO ( 22 NOVEMBRO) X TERMINAL JOÃO GOULART
23     44               1                                 ITITIOCA X CENTRO             1.0                                 ITITIOCA X CENTRO
58   44.0               1                                 ITITIOCA X CENTRO             1.0                                 ITITIOCA X CENTRO
24     45               1                                  CUBANGO X CENTRO             1.0                                  CUBANGO X CENTRO
59   45.0               1                                  CUBANGO X CENTRO             1.0                                  CUBANGO X CENTRO
25     46               1                         VÁRZEA DAS MOÇAS X CENTRO             1.0                         VÁRZEA DAS MOÇAS X CENTRO
47     47               1                           Vital Brasil x Terminal             1.0                           Vital Brasil x Terminal
51   47.0               1                           Vital Brasil x Terminal             1.0                           Vital Brasil x Terminal
48    47A               1                          Circular / Campus da UFF             1.0                          Circular / Campus da UFF
49    47B               1                       Museu / Mac / Campus da UFF             1.0                       Museu / Mac / Campus da UFF
26     48               1                              RIO DO OURO X CENTRO             1.0                              RIO DO OURO X CENTRO
27    48B               1                                   BOSQUE X CENTRO             1.0                                   BOSQUE X CENTRO
28   48SP               1                SERVIÇO PARCIAL - RUA PRES. BACKER             1.0                SERVIÇO PARCIAL - RUA PRES. BACKER
29   49.1               1                                   BONFIM X BARCAS             1.0                                   BONFIM X BARCAS
30   49.2               1                                 SÃO JOSÉ X LEADER             1.0                                 SÃO JOSÉ X LEADER
31     52               1                BALDEADOR X ITAIPU (VIA CANTAGALO)             1.0                BALDEADOR X ITAIPU (VIA CANTAGALO)
32    52A               1                              BALDEADOR X CHARITAS             1.0                              BALDEADOR X CHARITAS
33     53               1                               SANTA ROSA X CENTRO             1.0                               SANTA ROSA X CENTRO
34     54               1                                SAPÊ X PIRATININGA             1.0                                SAPÊ X PIRATININGA
35    55A               1                    VÁRZEA DAS MOÇAS X PIRATININGA             1.0                    VÁRZEA DAS MOÇAS X PIRATININGA
36     57               1         SANTA ROSA X CENTRO (VIA FAGUNDES VARELA)             1.0         SANTA ROSA X CENTRO (VIA FAGUNDES VARELA)
37     60               1                           ILHA CONCEIÇÃO X ICARAÍ             1.0                           ILHA CONCEIÇÃO X ICARAÍ
60   60.0               1                           ILHA CONCEIÇÃO X ICARAÍ             1.0                           ILHA CONCEIÇÃO X ICARAÍ
45     61               1                            VENDA DA CRUZ X ICARAI             1.0                            VENDA DA CRUZ X ICARAI
52   61.0               1                            VENDA DA CRUZ X ICARAI             1.0                            VENDA DA CRUZ X ICARAI
38     62               1                          SANTA BÁRBARA X CHARITAS             1.0                          SANTA BÁRBARA X CHARITAS
61   62.0               1                          SANTA BÁRBARA X CHARITAS             1.0                          SANTA BÁRBARA X CHARITAS
39    66C               1                     SAO LOURENCO X AMARAL PEIXOTO             1.0                     SAO LOURENCO X AMARAL PEIXOTO
40     67               1                         MORRO DO CASTRO X NITEROI             1.0                         MORRO DO CASTRO X NITEROI
53   67.0               1                         MORRO DO CASTRO X NITEROI             1.0                         MORRO DO CASTRO X NITEROI
41    OC1               1                                        OCEÂNICA 1             1.0                                        OCEÂNICA 1
42    OC2               1                                        OCEÂNICA 2             1.0                                        OCEÂNICA 2
43    OC3               1                                        OCEÂNICA 3             1.0                                        OCEÂNICA 3
44   OC3A               1                                       OCEÂNICA 3A             1.0                                       OCEÂNICA 3A

{'exact_full_name_intersection': 0, 'normalized_full_name_intersection': 1, 'ticket_unique_names': 58, 'mobility_unique_names': 51}

### Dominant full names for shared route codes (diagnostic; no fuzzy forcing)

   route                               Ticket_view_type                                 Mobility_lineName  exact  case_space_accent_equal
0     15                     ILHA DA CONCEIÇÃO - CENTRO                           ILHA CONCEIÇÃO X CENTRO  False                    False
1     21                               FONSECA - CENTRO                    BONFIM X TERMINAL JOÃO GOULART  False                    False
2     22                        LARGO DO MOURA - CENTRO                           BONFIM X AMARAL PEIXOTO  False                    False
3    26A                          MORRO DO CÉU - CENTRO                                MORRO CÉU X CENTRO  False                    False
4     28     CENTRO CIRCULAR LARGO CRAVINHO VIA FONSECA                LARGO DO CRAVINHO X AMARAL PEIXOTO  False                    False
5     30                                 MARTINS TORRES                                    Martins Torres  False                     True
6     31                       PONTA DA AREIA - BELTRÃO                                    PONTA DA AREIA  False                    False
7     32                             CACHOEIRA - CENTRO                   CACHOEIRA X TERMINAL RODOVIARIO  False                    False
8     33                              JURUJUBA - CENTRO                    JURUJUBA X TERMINAL RODOVIARIO  False                    False
9    34A                  L.B. - CENTRO (VIA V. JARDIM)                         LARGO DA BATALHA X CENTRO  False                    False
10    35                              BALDEDOR - CENTRO                                BALDEADOR X CENTRO  False                    False
11    36                                  SAPE - CENTRO                                     SAPÊ X CENTRO  False                    False
12    37                      PARQUE DA COLINA - CENTRO                         PARQUE DA COLINA X CENTRO  False                    False
13   38A          ITAIPU - CENTRO (VIA ENGENHO DO MATO)                 ITAIPU X CENTRO (VIA ENG DO MATO)  False                    False
14   39A              PIRATININGA - CENTRO (VIA CAFUBA)                              PIRATININGA X CENTRO  False                    False
15    40                                MACEIO - CENTRO                                   MACEIÓ X CENTRO  False                    False
16  41BC   VENDA DA CRUZ - CENTRO VIA BENJAMIN CONSTANT  VENDA DA CRUZ X TERMINAL - VIA BENJAMIN CONSTANT  False                    False
17  41JB         VENDA DA CRUZ - CENTRO VIA JOÃO BRASIL        VENDA DA CRUZ X TERMINAL - VIA JOAO BRASIL  False                    False
18   42T              BARRETO - CENTRO (VIA RODOVIÁRIA)                          VENDA DA CRUZ X TERMINAL  False                    False
19  43.2                  CIRCULAR VIA 22 DE NOVEMBRO A    CUBANGO ( 22 NOVEMBRO) X TERMINAL JOÃO GOULART  False                    False
20    44                              ITITIOCA - CENTRO                                 ITITIOCA X CENTRO  False                    False
21    45                               CUBANGO - CENTRO                                  CUBANGO X CENTRO  False                    False
22    46                      VÁRZEA DAS MOÇAS - CENTRO                         VÁRZEA DAS MOÇAS X CENTRO  False                    False
23    47                                   CANTO DO RIO                           Vital Brasil x Terminal  False                    False
24   47A                       CAMPUS DA UFF - CIRCULAR                          Circular / Campus da UFF  False                    False
25   47B                      CAMPUS DA UFF - VIA MUSEU                       Museu / Mac / Campus da UFF  False                    False
26    48                           RIO DO OURO - CENTRO                              RIO DO OURO X CENTRO  False                    False
27   48B                                BOSQUE - CENTRO                                   BOSQUE X CENTRO  False                    False
28  48SP                  RIO DO OURO - PRAIA DE ICARAI                SERVIÇO PARCIAL - RUA PRES. BACKER  False                    False
29  49.1                     CIRCULAR VIA D LIMA CASTRO                                   BONFIM X BARCAS  False                    False
30  49.2                     CIRCULAR VIA D LIMA CASTRO                                 SÃO JOSÉ X LEADER  False                    False
31    52             BALDEADOR - ITAIPU (VIA CANTAGALO)                BALDEADOR X ITAIPU (VIA CANTAGALO)  False                    False
32   52A                           BALDEADOR - CHARITAS                              BALDEADOR X CHARITAS  False                    False
33    53                            SANTA ROSA - CENTRO                               SANTA ROSA X CENTRO  False                    False
34    54                             SAPE - PIRATININGA                                SAPÊ X PIRATININGA  False                    False
35   55A  VARZEA DAS MOÇAS X PIRATININGA - (VIA CAFUBÁ)                    VÁRZEA DAS MOÇAS X PIRATININGA  False                    False
36    57              (CIRCULAR VIA F. VARELA/M. FRIAS)         SANTA ROSA X CENTRO (VIA FAGUNDES VARELA)  False                    False
37    60                     ILHA DA CONCEIÇÃO - ICARAÍ                           ILHA CONCEIÇÃO X ICARAÍ  False                    False
38    61                         VENDA DA CRUZ - ICARAÍ                            VENDA DA CRUZ X ICARAI  False                    False
39    62                             FONSECA - CHARITAS                          SANTA BÁRBARA X CHARITAS  False                    False
40   66C               SÃO LOURENÇO - CENTRO (CIRCULAR)                     SAO LOURENCO X AMARAL PEIXOTO  False                    False
41    67                       CENTRO X MORRO DO CASTRO                         MORRO DO CASTRO X NITEROI  False                    False
42   OC1                PIRATININGA X CENTRO (VIA BHLS)                                        OCEÂNICA 1  False                    False
43   OC2                   ITAIPU X CENTRO - (VIA BHLS)                                        OCEÂNICA 2  False                    False
44   OC3           ITAIPU X CENTRO - (VIA PRAIA ICARAÍ)                                        OCEÂNICA 3  False                    False
45  OC3A            ITAIPU X CENTRO VIA ENGENHO DO MATO                                       OCEÂNICA 3A  False                    False

In [6]:
detail_rows=[]
for r,ds in route_details.items(): detail_rows.append({"route_name":r,"distinct_route_detail_id":len(ds),"route_detail_ids":" | ".join(sorted(ds))})
detail_id_rows=[]
for d in tix_detail_route:
    detail_id_rows.append({"route_detail_id":d,"n_route_name":len(tix_detail_route[d]),"n_view_type":len(tix_detail_view[d]),"n_company":len(tix_detail_company[d]),"route_names":" | ".join(sorted(tix_detail_route[d])),"companies":" | ".join(sorted(tix_detail_company[d]))})
display(Markdown("## `route_detail_id` empirical structure")); display(pd.DataFrame(detail_rows).sort_values(["distinct_route_detail_id","route_name"],ascending=[False,True])); display(pd.DataFrame(detail_id_rows).sort_values(["n_route_name","route_detail_id"],ascending=[False,True]))
display(Markdown("**Interpretation rule:** this establishes only within-Ticket relationships. Association with `tripId`, `direction`, and `headsign` is tested after high-confidence temporal pairing in Notebook 03; equality is never assumed."))

## `route_detail_id` empirical structure

   route_name  distinct_route_detail_id route_detail_ids
48         28                         2        2498 | 41
28       41BC                         2        2500 | 43
35       41JB                         2        2501 | 45
43       42SL                         2       2505 | 385
37        42T                         2       2504 | 383
15         61                         2        2502 | 47
41        026                         1               66
45         15                         1               87
32         17                         1             2731
40        17J                         1             2744
25         21                         1               62
42         22                         1               63
21       24.A                         1               88
44        26A                         1               69
57          3                         1               86
12         30                         1              178
16         31                         1               67
17         32                         1             2732
9          33                         1             2733
29        33F                         1             2745
38         34                         1             2718
26        34A                         1             2740
10         35                         1             2712
1          36                         1             2726
39         37                         1             2734
13        38A                         1             2717
5         39A                         1             2729
19         40                         1             2735
52       43.2                         1               74
6          44                         1             2727
7          45                         1             2728
0          46                         1             2713
54        46P                         1             2864
3          47                         1              179
55        47A                         1              180
33        47B                         1              181
11         48                         1             2714
53        48B                         1             2719
50       48SP                         1             2725
27       49.1                         1               75
24       49.2                         1               84
30         52                         1             2715
46        52A                         1             2720
22         53                         1             2736
47         54                         1             2737
31        55A                         1             2721
51         56                         1             2716
36         57                         1             2739
34      580.M                         1               78
20         60                         1               90
56         62                         1               68
23        62B                         1               77
49        66C                         1              387
4          67                         1             2461
18        OC1                         1             2730
8         OC2                         1             2722
14        OC3                         1             2723
2        OC3A                         1             2724

   route_detail_id  n_route_name  n_view_type  n_company route_names companies
12             178             1            1          1          30        27
3              179             1            1          1          47        27
58             180             1            1          1         47A        27
33             181             1            1          1         47B        27
4             2461             1            1          1          67         2
51            2498             1            1          1          28        11
59            2500             1            1          1        41BC        11
60            2501             1            1          1        41JB        11
47            2502             1            1          1          61        11
37            2504             1            1          1         42T         2
43            2505             1            1          1        42SL         2
10            2712             1            1          1          35        56
0             2713             1            1          1          46        56
11            2714             1            1          1          48        56
30            2715             1            1          1          52        56
54            2716             1            1          1          56        56
13            2717             1            1          1         38A        56
38            2718             1            1          1          34        56
56            2719             1            1          1         48B        56
48            2720             1            1          1         52A        56
31            2721             1            1          1         55A        56
8             2722             1            1          1         OC2        56
14            2723             1            1          1         OC3        56
2             2724             1            1          1        OC3A        56
53            2725             1            1          1        48SP        56
1             2726             1            1          1          36        56
6             2727             1            1          1          44        56
7             2728             1            1          1          45        56
5             2729             1            1          1         39A        56
18            2730             1            1          1         OC1        56
32            2731             1            1          1          17        56
17            2732             1            1          1          32        56
9             2733             1            1          1          33        56
39            2734             1            1          1          37        56
19            2735             1            1          1          40        56
22            2736             1            1          1          53        56
49            2737             1            1          1          54        56
36            2739             1            1          1          57        56
26            2740             1            1          1         34A        56
40            2744             1            1          1         17J        56
29            2745             1            1          1         33F        56
57            2864             1            1          1         46P        56
46             383             1            1          1         42T        11
50             385             1            1          1        42SL        11
52             387             1            1          1         66C        11
62              41             1            1          1          28         2
28              43             1            1          1        41BC         2
35              45             1            1          1        41JB         2
15              47             1            1          1          61         2
25              62             1            1          1          21         3
42              63             1            1          1          22         3
41              66             1            1          1         026         3
16              67             1            1          1          31         3
61              68             1            1          1          62         3
44              69             1            1          1         26A         3
55              74             1            1          1        43.2         3
27              75             1            1          1        49.1         3
23              77             1            1          1         62B         3
34              78             1            1          1       580.M         3
24              84             1            1          1        49.2         3
63              86             1            1          1           3        22
45              87             1            1          1          15        22
21              88             1            1          1        24.A        22
20              90             1            1          1          60        22

**Interpretation rule:** this establishes only within-Ticket relationships. Association with `tripId`, `direction`, and `headsign` is tested after high-confidence temporal pairing in Notebook 03; equality is never assumed.

## Notebook 01 interpretation guide

Use the displayed tables to assess A–C. A Ticket key of `(company_number, vehicle_number)` is required if the multi-company table is non-empty; otherwise `vehicle_number` is empirically globally unique for this month. Abrupt Mobility first/last spans are clues, not proof, of transponder replacement. Route-code overlap percentages—not full-name similarity—determine whether route is a viable shared key.